extends: default.yaml
paths:
  output_dir: ./outputs/ojha_full
data:
  train_root: ./datasets/ForenSynths/train
  val_root: ./datasets/ForenSynths/val
  test_root: ./datasets/UniversalFakeDetect_test
  train_classes: [car, cat, chair, horse]
  test_sets: [dalle, glide_100_10, glide_100_27, glide_50_27, guided, ldm_100, ldm_200, ldm_200_cfg]
